# Intro

Jon Messier

2/27/2023

[Learn WK 14: Using the Yelp API practice](https://login.codingdojo.com/m/376/12529/88073)

Using the Yelp API (Practice)

For this assignment you will practice with the Yelp API and the concept of pagination.

-    Use your API credentials to access the the Yelp api
-    You can choose the location and search term (food), but it must return more than 20 results so you can practice pagination!
-    Save the businesses as a records-oriented JSON file. (df.to_json(orient='records'))
-    Obtain ONLY the first two pages of results
-    Concatenate the results into one data frame

Here is a [sample solution](https://drive.google.com/file/d/1s-e5CmDGJ3Y-mfXvGIasUezY-tam5MNZ/view?usp=sharing) for you to explore.

In [1]:
#Import Classes
import json
from yelpapi import YelpAPI
import pandas as pd

In [2]:
with open('/Users/jonme/.secret/yelp_api.json') as f: #change the path to match YOUR path!!
    login = json.load(f)
login.keys()

dict_keys(['client-id', 'api-key'])

In [3]:
yelp_api = YelpAPI(login['api-key'], timeout_s=5.0)
yelp_api

In [4]:
# use our yelp_api variable's search_query method to perform our API call
search_results = yelp_api.search_query(location='Minneapolis, MN',
                                       term='brewery')
print(type(search_results))
print(search_results.keys())
search_results['total']

<class 'dict'>
dict_keys(['businesses', 'total', 'region'])

391

In [5]:
#Search results to a Dataframe
biz = pd.DataFrame(search_results['businesses'])
biz.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,5drXZULD_FYpBDCfpFqgfQ,dangerous-man-brewing-co-minneapolis-2,Dangerous Man Brewing Co,https://s3-media2.fl.yelpcdn.com/bphoto/2VprEG...,False,https://www.yelp.com/biz/dangerous-man-brewing...,369,"[{'alias': 'breweries', 'title': 'Breweries'}]",4.5,"{'latitude': 45.001118, 'longitude': -93.266388}",[],$$,"{'address1': '1300 2nd St NE', 'address2': '',...",+16122597283,(612) 259-7283,3433.459330
1,b1PSsTkD2sV3DhitJHHkPw,lakes-and-legends-brewing-minneapolis-3,Lakes & Legends Brewing,https://s3-media2.fl.yelpcdn.com/bphoto/RwWJJs...,False,https://www.yelp.com/biz/lakes-and-legends-bre...,162,"[{'alias': 'breweries', 'title': 'Breweries'},...",4.5,"{'latitude': 44.9689411, 'longitude': -93.2795...",[],$$,"{'address1': '1368 Lasalle Ave', 'address2': N...",+16129996020,(612) 999-6020,1425.516649

In [6]:
len(search_results['businesses'])

20

In [7]:
search_results = yelp_api.search_query(location='Minneapolis, MN',
                                       term='brewery', offset=20)
biz20 = pd.DataFrame(search_results['businesses'])
biz20.head(2)

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,oTMyxjqY0CN1HuvkRQIPBA,northbound-smokehouse-and-brewpub-minneapolis-2,Northbound Smokehouse & Brewpub,https://s3-media3.fl.yelpcdn.com/bphoto/W4S1_K...,False,https://www.yelp.com/biz/northbound-smokehouse...,434,"[{'alias': 'smokehouse', 'title': 'Smokehouse'...",4.0,"{'latitude': 44.934272, 'longitude': -93.232482}","[pickup, delivery]",$$,"{'address1': '2716 E 38th St', 'address2': '',...",+16122081450,(612) 208-1450,4625.612391
1,TGQtPSvmCumDCiIWPEhF2A,fulton-brewery-minneapolis,Fulton Brewery,https://s3-media4.fl.yelpcdn.com/bphoto/YeOi-b...,False,https://www.yelp.com/biz/fulton-brewery-minnea...,181,"[{'alias': 'breweries', 'title': 'Breweries'}]",4.0,"{'latitude': 44.984937, 'longitude': -93.279123}",[],$$,"{'address1': '414 6th Ave N', 'address2': '', ...",+16123333208,(612) 333-3208,2122.433222

In [8]:
## concatenate the previous results and new results. 
businesses = pd.concat([biz, biz20],
                      ignore_index=True)
display(businesses.head(3), businesses.tail(3))

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,5drXZULD_FYpBDCfpFqgfQ,dangerous-man-brewing-co-minneapolis-2,Dangerous Man Brewing Co,https://s3-media2.fl.yelpcdn.com/bphoto/2VprEG...,False,https://www.yelp.com/biz/dangerous-man-brewing...,369,"[{'alias': 'breweries', 'title': 'Breweries'}]",4.5,"{'latitude': 45.001118, 'longitude': -93.266388}",[],$$,"{'address1': '1300 2nd St NE', 'address2': '',...",+16122597283,(612) 259-7283,3433.459330
1,b1PSsTkD2sV3DhitJHHkPw,lakes-and-legends-brewing-minneapolis-3,Lakes & Legends Brewing,https://s3-media2.fl.yelpcdn.com/bphoto/RwWJJs...,False,https://www.yelp.com/biz/lakes-and-legends-bre...,162,"[{'alias': 'breweries', 'title': 'Breweries'},...",4.5,"{'latitude': 44.9689411, 'longitude': -93.2795...",[],$$,"{'address1': '1368 Lasalle Ave', 'address2': N...",+16129996020,(612) 999-6020,1425.516649
2,KAJtbn62rJJuyp5vcd3TXg,pryes-brewing-minneapolis-2,Pryes Brewing,https://s3-media2.fl.yelpcdn.com/bphoto/SXeeiT...,False,https://www.yelp.com/biz/pryes-brewing-minneap...,133,"[{'alias': 'breweries', 'title': 'Breweries'}]",4.5,"{'latitude': 44.99353, 'longitude': -93.27633}",[delivery],$$,"{'address1': '1401 W River Rd N', 'address2': ...",+16127877937,(612) 787-7937,2817.618545

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
37,bDIUhf2LOzN1f3waZQF-PA,waldmann-brewery-saint-paul-2,Waldmann Brewery,https://s3-media1.fl.yelpcdn.com/bphoto/ZOJ8JS...,False,https://www.yelp.com/biz/waldmann-brewery-sain...,159,"[{'alias': 'breweries', 'title': 'Breweries'},...",4.5,"{'latitude': 44.9383265439193, 'longitude': -9...",[delivery],$$,"{'address1': '445 Smith Ave N', 'address2': ''...",+16512221857,(651) 222-1857,12487.864910
38,N20WlHUzfwZZcryJAjnrnQ,sociable-cider-werks-minneapolis,Sociable Cider Werks,https://s3-media1.fl.yelpcdn.com/bphoto/vqkukH...,False,https://www.yelp.com/biz/sociable-cider-werks-...,213,"[{'alias': 'breweries', 'title': 'Breweries'},...",4.0,"{'latitude': 45.00453964, 'longitude': -93.244...",[],$,"{'address1': '1500 Fillmore St NE', 'address2'...",+16127580105,(612) 758-0105,4030.585045
39,dH9wQYR49whjjRaYIvPRuw,bk-tap-haus-restaurant-saint-michael,BK Tap Haus Restaurant,https://s3-media2.fl.yelpcdn.com/bphoto/V627vM...,False,https://www.yelp.com/biz/bk-tap-haus-restauran...,41,"[{'alias': 'german', 'title': 'German'}, {'ali...",4.0,"{'latitude': 45.20963, 'longitude': -93.66554}",[delivery],NaN,"{'address1': '21 Main St S', 'address2': 'Ste ...",+17637779481,(763) 777-9481,41356.420870

In [9]:
#convert to JSON
biz_json = businesses.to_json(orient='records')

In [11]:
# Save it to a file
with open('Learn - WK14 - Yelp practive.json','w') as file:
    json.dump(biz_json,f)

ValueError: I/O operation on closed file.